language: node_js
node_js:
  - "node"
install: npm install
script: npm run unit
deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_API_KEY
    app:
      develop: synaptic-scout-staging
      master: synaptic-scout
  - provider: npm
    email: "code@tommilligan.net"
    api_key: "$NPM_API_KEY"
    on:
      all_branches: true
addons:
    srcclr: true